### ISSUE TITLE
FileNotFoundError Missing pdftotext

### ISSUE THREAD

**Issue by ghost** [weilu/moneycat#16]
```
## Upload Support PDF Statement
curl -X "POST" "https://q5i6ef1jfi.execute-api.ap-southeast-1.amazonaws.com/api/upload" \
     -H 'Authorization: eyJraWQiOiJNU2FGbnZ4ZnVXUEZHQ2Z1SDNpdDBKTDdOdVwvaTZ3ZjRlbmVkRGwrXC9ob2s9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJiYjdkY2RiMC05YjY5LTQwMTMtOTkzMy02MTlmNjdiMjA0OGYiLCJhdWQiOiIxNmljNGw2YW02a2NndTFqc2Y2YWY5ZXZycCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJldmVudF9pZCI6IjVmMGJmNTk1LThkNjYtMTFlOC1iOTI4LWJmZWFkNWE0MzJlNiIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTMyMjMzMTQ1LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGhlYXN0LTFfRHREdldaRm1jIiwiY29nbml0bzp1c2VybmFtZSI6ImhpQHhpbnlhbmcubGkiLCJleHAiOjE1MzIyMzY3NDUsImlhdCI6MTUzMjIzMzE0NSwiZW1haWwiOiJoaUB4aW55YW5nLmxpIn0.CtZ8xDPDrMhSEQLXNvJyGR4XK4pHjIhLMAL1evFKLk1GnPk3XsIuV31E2D6vImeKG-EiNqMpVwJL-AyRDd-95pku2QXz3reaNea2G4M4fuHCqr3irzE81FKk1GH9MLiaYBhoYJoJa7QxunvCpxVUBBReFwYbs0wD-OLJXBeXQWFhNqii6tbiOAolao5Fgd85pGqa5K2CMQmvG__0BL-1xvvv8CgsQfUesm6BMrWLDg1oydZBaJo_CaqbgB-mnchHVoEVmJRtvv8DMglauLIHYu6oNDW8sRdOKRAbP9ueG-z8djNCiJ-TMVplJrTBKV-pGXTespviMoNtjcvamj237Q' \
     -H 'Content-Type: multipart/form-data; charset=utf-8; boundary=__X_PAW_BOUNDARY__' \
     -F "file="

```

500 Error

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 659, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 164, in upload
    env=dict(LD_LIBRARY_PATH=LIB_DIR))
  File "/var/task/chalicelib/pdftotxt.py", line 129, in process_pdf
    result = subprocess.check_output(command, stderr=subprocess.PIPE, **kwargs)
  File "/var/lang/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/var/lang/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/var/lang/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/var/lang/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/pdftotext'
```

**Comment by ghost** [comment]
```
## Upload Support PDF Statement
curl -X "POST" "https://q5i6ef1jfi.execute-api.ap-southeast-1.amazonaws.com/api/upload" \
     -H 'Content-Type: multipart/form-data; charset=utf-8; boundary=__X_PAW_BOUNDARY__' \
     -H 'Authorization: eyJraWQiOiJNU2FGbnZ4ZnVXUEZHQ2Z1SDNpdDBKTDdOdVwvaTZ3ZjRlbmVkRGwrXC9ob2s9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJiYjdkY2RiMC05YjY5LTQwMTMtOTkzMy02MTlmNjdiMjA0OGYiLCJhdWQiOiIxNmljNGw2YW02a2NndTFqc2Y2YWY5ZXZycCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJldmVudF9pZCI6IjVmMGJmNTk1LThkNjYtMTFlOC1iOTI4LWJmZWFkNWE0MzJlNiIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTMyMjMzMTQ1LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGhlYXN0LTFfRHREdldaRm1jIiwiY29nbml0bzp1c2VybmFtZSI6ImhpQHhpbnlhbmcubGkiLCJleHAiOjE1MzIyMzY3NDUsImlhdCI6MTUzMjIzMzE0NSwiZW1haWwiOiJoaUB4aW55YW5nLmxpIn0.CtZ8xDPDrMhSEQLXNvJyGR4XK4pHjIhLMAL1evFKLk1GnPk3XsIuV31E2D6vImeKG-EiNqMpVwJL-AyRDd-95pku2QXz3reaNea2G4M4fuHCqr3irzE81FKk1GH9MLiaYBhoYJoJa7QxunvCpxVUBBReFwYbs0wD-OLJXBeXQWFhNqii6tbiOAolao5Fgd85pGqa5K2CMQmvG__0BL-1xvvv8CgsQfUesm6BMrWLDg1oydZBaJo_CaqbgB-mnchHVoEVmJRtvv8DMglauLIHYu6oNDW8sRdOKRAbP9ueG-z8djNCiJ-TMVplJrTBKV-pGXTespviMoNtjcvamj237Q' \
     -H 'Accept: application/json' \
     -F "file=/Users/xili/Downloads/a.pdf"
```

**Comment by weilu** [comment]
Fix deployed to dev
