### ISSUE TITLE
ValueError Invalid Param fro Normalize Function

### ISSUE THREAD

**Issue by ghost** [weilu/moneycat#17]
```
## Upload Support PDF Statement
curl -X "POST" "https://q5i6ef1jfi.execute-api.ap-southeast-1.amazonaws.com/api/upload" \
     -H 'Content-Type: multipart/form-data; charset=utf-8; boundary=__X_PAW_BOUNDARY__' \
     -H 'Authorization: eyJraWQiOiJNU2FGbnZ4ZnVXUEZHQ2Z1SDNpdDBKTDdOdVwvaTZ3ZjRlbmVkRGwrXC9ob2s9IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJiYjdkY2RiMC05YjY5LTQwMTMtOTkzMy02MTlmNjdiMjA0OGYiLCJhdWQiOiIxNmljNGw2YW02a2NndTFqc2Y2YWY5ZXZycCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJldmVudF9pZCI6ImMzNGJiZDE1LThkNzktMTFlOC1hYWIyLTg5NGYwZGFjNWQ1NyIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNTMyMjQxNDc0LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtc291dGhlYXN0LTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGhlYXN0LTFfRHREdldaRm1jIiwiY29nbml0bzp1c2VybmFtZSI6ImhpQHhpbnlhbmcubGkiLCJleHAiOjE1MzIyNDUwNzQsImlhdCI6MTUzMjI0MTQ3NCwiZW1haWwiOiJoaUB4aW55YW5nLmxpIn0.WHQhNyT_ecOlusnBC5k-vgoyiuL039opbd-nrMhb1lNXKe1CiAjRcWJCDJPyJkP7Pnj_Z9Cu4CSHAlEvCzcP-TU5bKvVFavczDtv4n38lZSDc1GaJJ7jVmW_oXBaGybUyF1TWEZL8hSsbdasvVIz0YIZSgezRttglAVAS34-Y-UoJs7RYX3dlScc3OL32aW3XHWqbnKdXR07A5j3Nz7NLJTl_08Heb93g2rKe-sl3BTcZfkFNANF70FugasECL4tEjyrf4yYif4HcYqNlY77TsO7Nx3d5Gplw2v1dTVBkEssWmd2G1GEU9WDqGvzK6s6abnms5YI-cinhTGYSH0s5w' \
     -H 'Accept: application/json' \
     -F "file=@/Users/xili/Downloads/a.pdf"

```

Response

```
Traceback (most recent call last):
  File "/var/task/chalice/app.py", line 659, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 178, in upload
    pred = classifier.predict(transformer.transform(df['description']))
  File "/var/task/sklearn/feature_extraction/text.py", line 1410, in transform
    return self._tfidf.transform(X, copy=False)
  File "/var/task/sklearn/feature_extraction/text.py", line 1114, in transform
    X = normalize(X, norm=self.norm, copy=False)
  File "/var/task/sklearn/preprocessing/data.py", line 1412, in normalize
    estimator='the normalize function', dtype=FLOAT_DTYPES)
  File "/var/task/sklearn/utils/validation.py", line 462, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 1301)) while a minimum of 1 is required by the normalize function.

```

**Comment by weilu** [comment]
curl works fine, was dev tool paw's problem
